url: http://www.atlabs.xyz/
baseurl: /at-labs.github.io

# Site settings
title: ATLabs - Ideas for Auckland
email: mailto:info@atlabs.xyz
description: "Test description."

timezone: Pacific/Auckland
markdown: kramdown
highlighter: rouge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: comments
    url: https://gitter.im/at-labs/Lobby
  - title: tasks
    url: https://waffle.io/AT-Labs/at-api
  - title: github
    url: http://github.com/AT-Labs

# Postal address (add as many lines as necessary)
address:
  - line: 34 Drake St,
  - line: Auckland, 1010

# Build settings
permalink: pretty
